export const data = [
  {
    id: 1,
    type: "Screw And Bolts",
    image: "/hex-bolt-screw.jpg",
    name: "Hex Bolts And Screw",
    grade: "4.6, 5.6,8.8, 10.9, Stainless Steel A2-70 (SS304), A4-70 (SS316)",
    sizeRange: "M4-M64",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "We manufacture Hex Bolts and Full Thread Screws as per ISO Grades 4.6, 5.6, 6.8, 8.8, 10.9 & 12.9. Our Manufacturing Capacity for Headed Products is from M8 X 50 to M100 X 1200 & for Non Headed Products from M8 to M100 & Length up to 3 Meters. Bolts can be provided in various surface finishes like Zinc Trivalent Plating, Hot Dip Galvanized, PTFE and Zinc Flake coatings",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 2,
    image: "/hhb.jpeg",
    type: "Screw And Bolts",
    name: "HSFG Heavy Hex Bolts",
    grade: "8.8S, 10.9S, A325M",
    sizeRange: "M16-M42",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "We manufacture and supply High Strength Structural Bolt Assembly (HSFG/HSS Bolt Assembly) consisting of a Heavy Hex Bolt, Heavy Hex Nut & Hardened Washer. Structural Bolts shall conform to IS, ISO, EN or ASTM Standard or as per Customer Requirements. Direct Tension Load Indicating (DTI) washers are also supplied with the Structural Bolts as per customer requirements. All bolts can be supplied in various surface finishes as Black Phosphated, Zinc Plated, Hot Dip Galvanised or Zinc Flake Coating. ",
    materials: "ALLOY STEEL",
  },

  {
    id: 3,
    image: "/fb.jpg",
    type: "Screw And Bolts",
    name: "Foundation Bolts",
    grade: "Mild Steel 4.6, HT 8.8, HT 10.9",
    sizeRange: "M12-M100",
    finishing: "NATURAL, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "FOUNDATION BOLTS / ANCHOR BOLTS AS PER CUSTOMER SPECIFICATIONS AND DRAWINGS",
    materials: "MILD STEEL, ALLOY STEEL",
  },
  {
    id: 4,
    image: "/ub.jpeg",
    type: "Screw And Bolts",
    name: "U Bolts",
    grade: "4.6 ,8.8, 10.9, Stainless Steel",
    sizeRange: "",
    finishing: "NATURAL, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "U-BOLTS FOR PIPE SUPPORTS",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 5,
    image: "/fh.jpg",
    type: "Screw And Bolts",
    name: "Flange Head Bolts/Screws",
    grade: "Mild Steel 4.6, HT 8.8, HT 10.9, Stainless Steel",
    sizeRange: "M6-M16",
    finishing: "",
    desc: "",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 6,
    image: "/scs.jpg",
    name: "Socket Cap Screws",
    type: "Screw And Bolts",
    grade: "8.8, 12.9, A2-70 (SS304), A4-70 (SS316)",
    sizeRange: "M4-M42",
    finishing: "PHOSPHATED BLACK, ZINC PLATED",
    desc: "Socket Head Cap Screws (known as Allen Bolts)",
    materials: "ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 7,
    image: "/bh.jpg",
    name: "Button Head Screws",
    type: "Screw And Bolts",
    grade: "8.8, 12.9, A2-70 (SS304), A4-70 (SS316)",
    sizeRange: "M4-M20",
    finishing: "PHOSPHATED BLACK, ZINC PLATED",
    desc: "",
    materials: "ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 8,
    image: "/cbs.jpg",
    name: "Countersunk Bolts/Screws",
    type: "Screw And Bolts",
    grade: "8.8, 12.9, A2-70 (SS304), A4-70 (SS316)",
    sizeRange: "M4-M20",
    finishing: "PHOSPHATED BLACK, ZINC PLATED",
    desc: "",
    materials: "ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 9,
    image: "/sss.jpg",
    name: "Socket Set Screws/Grub Screws",
    type: "Screw And Bolts",
    grade: "8.8, 12.9, A2-70 (SS304), A4-70 (SS316)",
    sizeRange: "M4-M20",
    finishing: "PHOSPHATED BLACK, ZINC PLATED",
    desc: "",
    materials: "ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 10,
    image: "/cb.jpg",
    name: "Carriage Bolts",
    type: "Screw And Bolts",
    grade: "4.6,8.8, Stainless Steel A2-70 (SS304)",
    sizeRange: "M6 - M12",
    finishing: "NATURAL, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 11,
    image: "/st.jpg",
    name: "Studs and Threaded Rods",
    type: "Stud And Threaded Bars",
    grade: "Mild Steel 4.6, HT 8.8, HT 10.9, Stainless Steel B8, ASTM A193 B7",
    sizeRange: "M6 - M64",
    finishing:
      "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED, GEOMET, PTFE COATING",
    desc: "We manufacture Fully Threaded Stud with Nut and Washer Assemblies Conforming to ASTM A 193/ASTM A 194 Standard and various other standards. Studs can be manufactured as per customer specifications. All studs can be supplied in various surface finishes Phosphated, Xylan PTFE, Hot Dip Galvanized and Zinc Plated. ",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 12,
    image: "/SC.jpg",
    type: "Stud And Threaded Bars",
    name: "Shear Connectors",
    grade:
      "Shear connectors with Ceramic ferrules to suit the shear connectors are supplied. Depending upon the application, Bare Metal or Through Deck Ceramic Ferrules are supplied.",
    sizeRange:
      "Shank diameter 13, 16, 19, 22 and 25 mm are most commonly used worldwide, with varying lengths.",
    finishing: "",
    desc: "Mechanical properties & other requirements of studs shall confirm to the requirements of Type-B studs specified in AWS Dl.1/D1.lM or equivalent. Studs for welding with ceramic ferrules are provided with an aluminum tip as required by the welding process to facilitate the ignition of the arc, to stabilize the arc and to deoxidize the welding pool",
    materials:
      "Shear Stud Connector Shall be manufactured from cold drawn Wire Rods confirming the requirements of ASTM A 29 of grade designation SAE 1010 through SAE 1020 or equivalent, inclusive either semi-killed or killed (aluminium or silicon deoxidation).",
  },
  {
    id: 13,
    image: "/hn.jpg",
    name: "Hex Nuts",
    type: "Nuts",
    grade: "ISO Grade 4, 8, 10, Stainless Steel",
    sizeRange: "M4-M64",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "Nuts as per  grades 4, 8, 10, Stainless Steel A2-70, A4-70",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 14,
    image: "/hnn.jpg",
    name: "Heavy Hex Nuts",
    type: "Nuts",
    grade: "8S, 10S, A563",
    sizeRange: "M16-M42",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "Heavy Structural Nuts for HSFG Bolts/Assemblies",
    materials: "ALLOY STEEL",
  },
  {
    id: 15,
    image: "/nil.jpg",
    name: "Nylon Insert Lock Nuts - Nyloc Nuts",
    type: "Nuts",
    grade: "ISO Grade 4, 8, 10, Stainless Steel",
    sizeRange: "M3-M30",
    finishing: "ZINC PLATED",
    desc: "Nylon Insert Lock Nuts as per standard and customer drawings",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 16,
    image: "/pfw.jpg",
    name: "Plain Flat Washers",
    type: "Washers",
    grade: "Mild Steel, Stainless Steel",
    sizeRange: "M3-M100",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "Plain washers as per standard and customer specifications",
    materials: "MILD STEEL, ALLOY STEEL, STAINLESS STEEL",
  },
  {
    id: 17,
    image: "/hw.jpg",
    name: "Hardened Washers",
    type: "Washers",
    grade: "Carbon Steel",
    sizeRange: "M12- M36",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "Hardened Washers for Structural Bolt Assemblies",
    materials: "Carbon Steel",
  },
  {
    id: 18,
    image: "/sw.jpg",
    name: "Spring Lock Washers & Conical Spring Washers",
    type: "Washers",
    grade: "Carbon Steel, Stainless Steel",
    sizeRange: "M3 - M30",
    finishing: "PHOSPHATED BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "Spring washers, which have axial flexibility and are used to prevent fastening or loosening due to vibrations",
    materials: "Carbon Steel, Stainless Steel",
  },
  {
    id: 19,
    image: "/dti.jpg",
    name: "DTI Washers- Load Indicating Washers",
    type: "Washers",
    grade: "Steel",
    sizeRange: "M16-M30",
    finishing: "ZINC PLATED, HOT DIP GALVANIZED",
    desc: "DTI's Load Indicating Washers are used to develop the correct tension when installing structural steel bolts A325 or IS3757",
    materials: "Steel",
  },
  {
    id: 20,
    image: "/tw.jpeg",
    name: "Taper Washers & Square Washers",
    type: "Washers",
    grade: "Mild Steel, Stainless Steel, Carbo Steel",
    sizeRange: "M12-M24",
    finishing: "BLACK, ZINC PLATED, HOT DIP GALVANIZED",
    desc: "We manufacture Taper washers as per Indian Standard 5372 (IS 5372-1975)/Din 434 (For Channels) & IS 5374 - 1975 (For I Beams)",
    materials: "Mild Steel, Stainless Steel, Alloy Steel",
  },
];
